/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2018-04-27 08:08:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(".\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>Dashboard Template for Bootstrap</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!-- head end -->\r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("          <h1 class=\"page-header\">注册系统</h1>\r\n");
      out.write("          \r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2\">\r\n");
      out.write("\t           <form class=\"form-horizontal\"   id=\"userInfo\" \r\n");
      out.write("\t           action=\"doRegister.do\" \r\n");
      out.write("\t           method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t          \r\n");
      out.write("\t         \r\n");
      out.write("\t\t    <fieldset>\r\n");
      out.write("\t\t      <div id=\"legend\" class=\"\">\r\n");
      out.write("\t\t        <legend class=\"\">请输入注册信息</legend>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">用户名</label>\r\n");
      out.write("\t\t           <div class=\"controls\">\t\t          \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t            <input type=\"text\" value=\"\" name='userName' placeholder=\"用户名\"  class=\"input-xlarge\" >\r\n");
      out.write("\t\t             <span>用户名注册后不可修改</span>  \r\n");
      out.write("\t\t            </div> \t\t        \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">密码</label>\r\n");
      out.write("\t\t           <div class=\"controls\">\t\t          \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t            <input type=\"text\" value=\"\" name='password' placeholder=\"密码\"  class=\"input-xlarge\" >\r\n");
      out.write("\t\t             <span>密码至少8位</span>  \r\n");
      out.write("\t\t            </div> \t\t        \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \t<div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">再次输入密码</label>\r\n");
      out.write("\t\t           <div class=\"controls\">\t\t          \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t            <input type=\"text\" value=\"\" name='repassword' placeholder=\"密码\"  class=\"input-xlarge\" >\r\n");
      out.write("\t\t             <span>密码至少8位</span>  \r\n");
      out.write("\t\t            </div> \t\t        \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">姓名</label>\r\n");
      out.write("\t\t         <div class=\"controls\">\r\n");
      out.write("\t\t            <input type=\"text\" name=\"realName\" value=\"\" placeholder=\"请输入真实姓名\" class=\"input-xlarge\">\r\n");
      out.write("\t\t            <span >真实姓名保存后将不可修改</span>\r\n");
      out.write("\t\t         </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">身份证号码</label>\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            <input type=\"text\" name=\"idCode\" value=\"\" placeholder=\"身份证号码\" class=\"input-xlarge\">\r\n");
      out.write("\t\t            <span>身份证号码为18位</span>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">联系电话</label>\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t           <input type=\"text\" name=\"telPhone\"  value=\"\" placeholder=\"电话号码\" class=\"input-xlarge\">\r\n");
      out.write("\t\t            <span>请输入电话号码</span>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t       <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">email</label>\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t           <input type=\"text\" name=\"email\"  value=\"\" placeholder=\"email\" class=\"input-xlarge\">\r\n");
      out.write("\t\t            <span>请输入email</span>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t          <label class=\"control-label\">头像</label>\r\n");
      out.write("\t\t          <br>\r\n");
      out.write("\t\t<img src=\"images/idcard.jpg\" width='150' height=\"150\">\r\n");
      out.write("\t\t          <!-- File Upload -->\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            <input class=\"input-file\" name=\"cardFaceImageFile\" id=\"cardFaceImageFile\" type=\"file\">\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t          <label class=\"control-label\"></label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Button -->\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            <input type=\"submit\" class=\"btn btn-primary\" value=\"注册\"/>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    </fieldset>\r\n");
      out.write("\t\t  </form>\r\n");
      out.write("            </div>\r\n");
      out.write("                  \r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\t\t<!-- footer begin -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script>window.jQuery || document.write('<script src=\"../../assets/js/vendor/jquery.min.js\"><\\/script>')</script>\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
