/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2018-05-27 13:40:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class toEditUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/head.jsp", Long.valueOf(1515901053582L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1524129010000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write(" ");
      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>航空订票系统</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">飞天航空订票系统</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/toUserCenter.do\">个人中心</a></li>\r\n");
      out.write("            <li><a href=\"helpout.do\">帮助中心</a></li>\r\n");
      out.write("           <!--  <li><a href=\"#\"></a></li>  -->\r\n");
      out.write("            <li><a href=\"logout.do\">注销</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <form class=\"navbar-form navbar-right\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("          <ul class=\"nav nav-sidebar\">\r\n");
      out.write("            <li class=\"firstmenu\"><a href=\"queryAirLine.do\" >查询航班信息</a></li>          \r\n");
      out.write("            <li  class=\"active\"><a href=\"queryAirLine.do\">我要订票</a></li>\r\n");
      out.write("            <li><a href=\"myorder.do?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">我的订单</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/listAdvice.do?userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">投诉建议</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("<!-- head end -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("          <h1 class=\"page-header\">个人中心</h1>\r\n");
      out.write("          \r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2\">\r\n");
      out.write("\t           <form class=\"form-horizontal\"   id=\"userInfo\" \r\n");
      out.write("\t           action=\"saveUser.do\" \r\n");
      out.write("\t           method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t          \r\n");
      out.write("\t         <input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t         <input type=\"hidden\" name=\"userName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t    <fieldset>\r\n");
      out.write("\t\t      <div id=\"legend\" class=\"\">\r\n");
      out.write("\t\t        <legend class=\"\">修改个人信息</legend>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div class=\"alert alert-warning\" role=\"alert\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">用户名</label>\r\n");
      out.write("\t\t           <div class=\"controls\">\t\t          \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t            <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name='userName' placeholder=\"用户名\"  class=\"input-xlarge\" disabled >\r\n");
      out.write("\t\t             <span>用户名注册后不可修改</span>  \r\n");
      out.write("\t\t            </div> \t\t        \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">请输入当前密码</label>\r\n");
      out.write("\t\t           <div class=\"controls\">\t\t          \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t            <input type=\"password\" value=\"\" name='password' placeholder=\"当前密码\"  class=\"input-xlarge\" >\r\n");
      out.write("\t\t             <span>密码至少8位</span>  \r\n");
      out.write("\t\t            </div> \t\t        \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">密码</label>\r\n");
      out.write("\t\t           <div class=\"controls\">\t\t          \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t            <input type=\"password\" value=\"\" name='newPassword' placeholder=\"新密码\"  class=\"input-xlarge\" >\r\n");
      out.write("\t\t             <span>密码至少8位</span>  \r\n");
      out.write("\t\t            </div> \t\t        \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \t<div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">再次输入密码</label>\r\n");
      out.write("\t\t           <div class=\"controls\">\t\t          \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t            <input type=\"password\" value=\"\" name='repassword' placeholder=\"密码\"  class=\"input-xlarge\" >\r\n");
      out.write("\t\t             <span>密码至少8位</span>  \r\n");
      out.write("\t\t            </div> \t\t        \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">姓名</label>\r\n");
      out.write("\t\t         <div class=\"controls\">\r\n");
      out.write("\t\t            <input type=\"text\" name=\"realName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.realName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" placeholder=\"请输入真实姓名\" class=\"input-xlarge\">\r\n");
      out.write("\t\t            <span ></span>\r\n");
      out.write("\t\t         </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t   <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">身份证号码</label>\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            <input type=\"text\" name=\"idCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.idCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" placeholder=\"身份证号码\" class=\"input-xlarge\">\r\n");
      out.write("\t\t            <span>身份证号码为18位</span>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">联系电话</label>\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t           <input type=\"text\" name=\"telPhone\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.telPhone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" placeholder=\"电话号码\" class=\"input-xlarge\">\r\n");
      out.write("\t\t            <span>请输入电话号码</span>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t       <div class=\"control-group\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Text input-->\r\n");
      out.write("\t\t          <label class=\"control-label\" for=\"input01\">email</label>\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t           <input type=\"text\" name=\"email\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" placeholder=\"email\" class=\"input-xlarge\">\r\n");
      out.write("\t\t            <span>请输入email</span>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t          <label class=\"control-label\">头像</label>\r\n");
      out.write("\t\t          <br>\r\n");
      out.write("\t\t<img src=\"images/idcard.jpg\" width='150' height=\"150\">\r\n");
      out.write("\t\t          <!-- File Upload -->\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            <input class=\"input-file\" name=\"cardFaceImageFile\" id=\"cardFaceImageFile\" type=\"file\">\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    <div class=\"control-group\">\r\n");
      out.write("\t\t          <label class=\"control-label\"></label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <!-- Button -->\r\n");
      out.write("\t\t          <div class=\"controls\">\r\n");
      out.write("\t\t            <input type=\"submit\" class=\"btn btn-primary\" value=\"修改\"/>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    </fieldset>\r\n");
      out.write("\t\t  </form>\r\n");
      out.write("            </div>\r\n");
      out.write("                  \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("          ");
      out.write("\t\t<!-- footer begin -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script>window.jQuery || document.write('<script src=\"../../assets/js/vendor/jquery.min.js\"><\\/script>')</script>\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
